"""mock_sync_audit.py v1.0 — cross-step sync auditor for the mock/test track.

THE GAP THIS CLOSES (GAP-2026-08-13-MOCK-SYNC-AUDIT). notes_sync_audit.py
exists because "four of the five defects were found by a human reading files
— which is not a control." The mock/test track (Step 5 MockTestAnalyse →
Step 6 Blueprint/ScopedBlueprint → Step 7 MockTestCreate → Step 9
MockTestExplain → Step 11 MockDeliver, plus DeliveryFooter) had NO
equivalent: two manual cross-step audits (releases .15 and .16) each found
real producer↔consumer desyncs — stale retired filenames, engine self-test
pins that HALTed healthy sessions, deliverable-count drift, footer patterns
that never matched scoped papers, provenance stamps four versions stale.
Every one of those is mechanically checkable. This auditor is those checks,
run by CI on every change instead of by a human once.

Like its sibling: it checks AGREEMENT, not correctness — five specs and an
engine can be unanimously wrong and every check passes. It catches drift.

CHECKS (each compares one authority against another; none holds an opinion):
  MS-1 PIN-FLOOR      Engine self-test gates in Explain/PYQExplain must use
                      the FLOOR form; any "must print" line pinning an exact
                      SELF-TEST count is flagged, and every declared floor
                      (N >= K) is verified against the ENGINE'S ACTUAL
                      OUTPUT by running it (explain_engine --self-test /
                      --self-test-audit).
  MS-2 RETIRED-NAMES  Retired filename literals (Create_Complete) must not
                      appear inside any spec's code/text fences, outside the
                      explicit legacy allowlist (DeliveryFooter's LOCAL_ONLY
                      legacy block; MockDeliver's legacy-accept regex).
  MS-3 STAMP-PARITY   MockTestAnalyse's emitted provenance stamps
                      (framework_version / generated_by / "Generated by")
                      must carry the file's own header major.minor.
  MS-4 COUNT-CLAIMS   "EXACTLY <n> files" claims are banned in
                      MockTestAnalyse/MockTestCreate delivery prose — the
                      expected set must be DERIVED (the v5.36/v2.47 lesson);
                      a literal count re-drifts every time a file is added.
  MS-5 GATE-PRESENCE  Load-bearing cross-step gates must exist: P10/0 in
                      MockTestExplain; the paper_slug↔docx_slug hard stop in
                      MockDeliver; the scoped-series mocks_completed guard
                      and the /DUP stale-sibling detector in final_assembly.
  MS-6 SLUG-LITERALS  No spec python fence may build a deliverable filename
                      from the literal Mock{N} instead of pp.paper_slug
                      (the S13-4B-SCOPED-PATH class).
  MS-7 QINDEX-FIELDS  final_assembly's question_index writer must emit the
                      five contract fields; MockTestExplain's P10 reader
                      must not reference a per-question key outside them.
  MS-8 DLBL-PARITY    Every difficulty_labels fallback literal across specs
                      and engines must be the identical list.
  MS-9 FOOTER-STEP5   DeliveryFooter's Step-5 final list must know
                      exam_config.json and taxonomy.xlsx (count-drift
                      tripwire mirrored into the footer registry).
  MS-10 VERSION-PINS  Every "Framework_<X> vA.B[.C]" claim in any spec must
                      be <= that file's actual header version (a pin AHEAD
                      of the real file means the companion release never
                      shipped or the pin is fiction).
  MS-11 DELIVERY-SET-PARITY
                      MockTestAnalyse's Step-5 final delivery: the code's
                      unconditional/conditional deliverable sets (parsed from
                      the `delivery` construction) must be declared identically
                      by ALL FIVE prose sites — S11-2 PART B, S11-3 FINAL
                      DELIVERY, the checklist expected set, QV [19], and
                      S11-2 PART C — and the two ordered sites must list files
                      in the code's emission order. Third recurrence of the
                      count-drift class (v2.47 / v2.47.1 / v2.48.1 each fixed
                      only the sites someone grepped for); this ends the
                      grep-driven era. GAP-2026-08-14-S11-2-PARTB-UNFIXED.

USAGE
    python3 mock_sync_audit.py            # run all checks against the repo
    python3 mock_sync_audit.py --self-test

Tracked, repo-level auditor — NOT routed to any trigger (same standing as
validate_framework_md.py / notes_sync_audit.py / spec_name_audit.py).
Stdlib only; MS-1 shells out to explain_engine.py in the same directory.
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

SPECS = ['Framework_MockTestAnalyse.md', 'Framework_Blueprint.md',
         'Framework_ScopedBlueprint.md', 'Framework_MockTestCreate.md',
         'Framework_MockTestExplain.md', 'Framework_MockDeliver.md',
         'Framework_DeliveryFooter.md', 'Framework_PYQExplain.md']


def _read(name, root=None):
    return open(os.path.join(root or HERE, name), encoding='utf-8').read()


def _fences(text):
    """All ```python / ```text fenced bodies as one concatenated string."""
    out = []
    for m in re.finditer(r'```(?:python|text)\n(.*?)\n```', text, re.S):
        out.append(m.group(1))
    return '\n'.join(out)


def _header_version(text):
    m = re.match(r'^#\s*\S+\s+v(\d+(?:\.\d+)+)', text)
    return m.group(1) if m else None


# ── MS-1 ────────────────────────────────────────────────────────────────
def check_pin_floor(read=_read, run=None):
    """Returns list of problem strings."""
    problems = []
    floors = {}   # flag -> max declared floor
    for spec in ('Framework_MockTestExplain.md', 'Framework_PYQExplain.md'):
        text = read(spec)
        _lines = text.split('\n')
        for i, line in enumerate(_lines, 1):
            window = line + ' ' + (_lines[i] if i < len(_lines) else '')
            low = window.lower()
            if 'ust print' in low and re.search(r'SELF-TEST: \d+/\d+ PASS', window):
                problems.append(f"{spec} L{i}: exact self-test count pinned on a "
                                f"'must print' line — use the FLOOR form (N/N "
                                f"PASS with N >= K); exact pins HALT healthy "
                                f"sessions when the engine grows fixtures")
        for m in re.finditer(r'SELF-TEST: N/N PASS["\s,]*(?:with N\s*[=>]+\s*total[^;)]*?)?(?:AND\s+)?N\s*>=\s*(\d+)', text):
            floors['--self-test'] = max(floors.get('--self-test', 0), int(m.group(1)))
        for m in re.finditer(r'N/N PASS[",\s]*(?:with)?\s*N\s*>=\s*(\d+)', text):
            pass  # generic floors handled per-flag below
        for m in re.finditer(r'self-test-audit[^\n]*?N\s*>=\s*(\d+)', text):
            floors['--self-test-audit'] = max(floors.get('--self-test-audit', 0),
                                              int(m.group(1)))
        for m in re.finditer(r'N\s*>=\s*(\d+)[^\n]*?(?:core|before any\s*$)', text):
            floors['--self-test'] = max(floors.get('--self-test', 0), int(m.group(1)))
    runner = run or _run_explain_engine
    for flag, floor in sorted(floors.items()):
        actual = runner(flag)
        if actual is None:
            problems.append(f"explain_engine.py {flag}: could not parse an "
                            f"N/N PASS banner from its output")
        elif actual < floor:
            problems.append(f"explain_engine.py {flag}: prints {actual} "
                            f"fixtures but a spec floor demands >= {floor}")
    return problems


def _run_explain_engine(flag):
    try:
        r = subprocess.run([sys.executable,
                            os.path.join(HERE, 'explain_engine.py'), flag],
                           capture_output=True, text=True, timeout=300)
        m = re.search(r'SELF-TEST: (\d+)/(\d+) PASS', r.stdout or '')
        if m and m.group(1) == m.group(2):
            return int(m.group(1))
    except Exception:
        pass
    return None


# ── MS-2 ────────────────────────────────────────────────────────────────
_RETIRED = ['Create_Complete']
_RETIRED_ALLOW = [
    ('Framework_DeliveryFooter.md', 'Mock*_Create_Complete.docx'),
]


def check_retired_names(read=_read):
    problems = []
    for spec in SPECS:
        body = _fences(read(spec))
        for lit in _RETIRED:
            for i, line in enumerate(body.split('\n'), 1):
                if lit in line:
                    if any(spec == af and allow in line
                           for af, allow in _RETIRED_ALLOW):
                        continue
                    problems.append(f"{spec} (fence line {i}): retired name "
                                    f"'{lit}' in executable/contract text: "
                                    f"{line.strip()[:70]!r}")
    return problems


# ── MS-3 ────────────────────────────────────────────────────────────────
def check_stamp_parity(read=_read):
    problems = []
    text = read('Framework_MockTestAnalyse.md')
    hv = _header_version(text)
    if not hv:
        return ["Framework_MockTestAnalyse.md: no parseable header version"]
    mm = '.'.join(hv.split('.')[:2])
    pats = [r"framework_version: v(\d+\.\d+)",
            r"Framework_MockTestAnalyse v(\d+\.\d+)",
            r"Generated by Framework_MockTestAnalyse v(\d+\.\d+)"]
    body = _fences(text)
    for pat in pats:
        hits = list(re.finditer(pat, body))
        # PRESENCE (v2026.08.15.8). This check verifies LITERALS. A stamp built from
        # an f-string over a constant leaves nothing to match, so the pattern would
        # silently score 0 issues while verifying nothing — the same check-shaped
        # hole a non-compiling fence opened in audit_callgraph C6. A pattern that
        # matches NOTHING is therefore a finding in its own right: whoever removed
        # the last literal must either restore one or delete this pattern
        # deliberately, in its own commit, with a stated reason.
        if not hits:
            problems.append(f"Framework_MockTestAnalyse.md: no emitted stamp matches "
                            f"{pat!r} anywhere in this file's fences. MS-3 verifies "
                            f"LITERAL stamps; if they are now derived, this check is "
                            f"disarmed and reports success while checking nothing. "
                            f"Keep one literal per pattern, or remove the pattern on "
                            f"purpose.")
            continue
        for m in hits:
            if m.group(1) != mm:
                problems.append(f"Framework_MockTestAnalyse.md: emitted stamp "
                                f"{m.group(0)!r} != header major.minor v{mm} "
                                f"(the five-times-recurred stamp-drift class)")
    return problems


# ── MS-4 ────────────────────────────────────────────────────────────────
def check_count_claims(read=_read):
    problems = []
    for spec in ('Framework_MockTestAnalyse.md', 'Framework_MockTestCreate.md'):
        text = read(spec)
        for i, line in enumerate(text.split('\n'), 1):
            if line.lstrip().startswith('#'):
                continue    # changelog/header commentary may QUOTE old claims
            if re.search(r'EXACTLY \d+ files', line, re.I) \
                    or re.search(r'EXACTLY (TWO|THREE|FOUR|FIVE|SIX) files', line, re.I):
                problems.append(f"{spec} L{i}: literal deliverable count claim "
                                f"({line.strip()[:60]!r}) — the expected set "
                                f"must be DERIVED, never a hardcoded count")
    return problems


# ── MS-5 ────────────────────────────────────────────────────────────────
_GATES = [
    ('Framework_MockTestExplain.md', 'P10/0',
     'trigger-N ↔ uploaded-docx identity gate'),
    ('Framework_MockDeliver.md', 'paper_slug != docx_slug',
     'Step-11 upload identity hard stop'),
    ('final_assembly.py', "_new_prefix == 'MOCK'",
     'scoped-series mocks_completed guard'),
    ('final_assembly.py', 'G-COMMIT-COMPLETE/DUP',
     'stale-sibling duplicate detector'),
]


def check_gate_presence(read=_read):
    problems = []
    for fname, needle, label in _GATES:
        if needle not in read(fname):
            problems.append(f"{fname}: load-bearing gate MISSING — {label} "
                            f"(expected literal {needle!r}); a refactor "
                            f"deleted or renamed it")
    return problems


# ── MS-6 ────────────────────────────────────────────────────────────────
def check_slug_literals(read=_read):
    problems = []
    for spec in SPECS:
        body = _fences(read(spec))
        for i, line in enumerate(body.split('\n'), 1):
            if re.search(r"_Mock\{N\}_(Create|Explanation|Final)", line):
                problems.append(f"{spec} (fence line {i}): deliverable name "
                                f"built from literal Mock{{N}} instead of "
                                f"pp.paper_slug (the S13-4B-SCOPED-PATH "
                                f"class): {line.strip()[:70]!r}")
    return problems


# ── MS-7 ────────────────────────────────────────────────────────────────
_QINDEX_FIELDS = ('"q"', '"subtopic_id"', '"section"', '"subtopic"', '"difficulty"')
_P10_ALLOWED = {'q', 'subtopic_id', 'difficulty', 'questions', 'mock', 'paper_id'}


def check_qindex_fields(read=_read):
    problems = []
    fa = read('final_assembly.py')
    for f in _QINDEX_FIELDS:
        if f not in fa:
            problems.append(f"final_assembly.py: question_index writer no "
                            f"longer emits contract field {f}")
    text = read('Framework_MockTestExplain.md')
    if '## P10' in text:
        p10 = text.split('## P10', 1)[1].split('\n## ', 1)[0]
        for m in re.finditer(r"x\.get\('([a-z_]+)'\)", p10):
            if m.group(1) not in _P10_ALLOWED:
                problems.append(f"Framework_MockTestExplain.md P10 reads "
                                f"per-question key '{m.group(1)}' that the "
                                f"question_index producer contract does not "
                                f"emit")
    return problems


# ── MS-8 ────────────────────────────────────────────────────────────────
def check_dlbl_parity(read=_read, files=None):
    problems = []
    seen = {}
    scan = files or (SPECS + ['final_assembly.py', 'paper_pipeline.py',
                              'audit_canonical.py'])
    for fname in scan:
        try:
            text = read(fname)
        except FileNotFoundError:
            continue
        for m in re.finditer(
                r"difficulty_labels['\"]?\s*,\s*\[([^\]]+)\]", text):
            canon = re.sub(r'\s+', '', m.group(1)).replace('"', "'")
            seen.setdefault(canon, []).append(fname)
    if len(seen) > 1:
        detail = '; '.join(f"[{k}] in {sorted(set(v))}" for k, v in seen.items())
        problems.append(f"difficulty_labels fallback literals disagree: {detail}")
    return problems


# ── MS-9 ────────────────────────────────────────────────────────────────
def check_footer_step5(read=_read):
    problems = []
    text = read('Framework_DeliveryFooter.md')
    if 'FINAL DELIVERABLES' in text:
        seg = text.split('FINAL DELIVERABLES', 1)[1][:4000]
        for want in ('exam_config.json', 'taxonomy.xlsx'):
            if want not in seg:
                problems.append(f"Framework_DeliveryFooter.md: Step-5 final "
                                f"list missing {want} (the DELIVERY-COUNT-"
                                f"DRIFT class, footer side)")
    return problems


# ── MS-10 ───────────────────────────────────────────────────────────────
def _ver_tuple(v):
    return tuple(int(x) for x in v.split('.'))


def check_version_pins(read=_read, root=None):
    problems = []
    actual = {}
    for spec in SPECS:
        try:
            hv = _header_version(read(spec))
        except FileNotFoundError:
            hv = None
        if hv:
            actual[spec.replace('Framework_', '').replace('.md', '')] = hv
    for spec in SPECS:
        try:
            text = read(spec)
        except FileNotFoundError:
            continue
        for m in re.finditer(r'Framework_([A-Za-z]+) v(\d+(?:\.\d+)+)', text):
            name, claimed = m.group(1), m.group(2)
            if name in actual and name != spec.replace('Framework_', '').replace('.md', ''):
                if _ver_tuple(claimed) > _ver_tuple(actual[name]):
                    problems.append(f"{spec}: pins Framework_{name} "
                                    f"v{claimed}, but that file's actual "
                                    f"header is v{actual[name]} — the pinned "
                                    f"companion release does not exist")
    return problems


# ── MS-11 ───────────────────────────────────────────────────────────────
# DELIVERY-SET-PARITY. The third hand-fix of the DELIVERY-COUNT-DRIFT class
# (v2.47 → v2.47.1 → v2.48.1 → v2.48.2) proved grep-driven passes always miss
# a site. This check parses the delivery code's `delivery` construction into
# an UNCONDITIONAL and a CONDITIONAL set (an append guarded by a path-existence
# test is conditional; any other append, seed, or += is unconditional), then
# asserts every prose delivery site agrees:
#   full two-set parity + emission-order parity : S11-2 PART B, S11-3 FINAL
#   brace-set parity                            : pre-delivery checklist expected
#   weak parity (cond names present, first      : QV item [19], S11-2 PART C
#     "N mandatory" claim == |unconditional|)
# A site whose anchor cannot be found is itself a finding — renaming an anchor
# must not silently disable the guard. (GAP-2026-08-14-S11-2-PARTB-UNFIXED.)

_DELIV_NAME_RE = (r'(section_rules\.md|subtopic_manifest\.json|'
                  r'PYQ_Frequency\.xlsx|exam_config\.json|taxonomy\.xlsx|'
                  r'analysis_progress\.json|analysis_summary\.md)')

_VAR_HINTS = [('rules', 'section_rules.md'),
              ('manifest', 'subtopic_manifest.json'),
              ('xlsx', 'PYQ_Frequency.xlsx'),
              ('ecfg', 'exam_config.json'),
              ('tax', 'taxonomy.xlsx'),
              ('progress', 'analysis_progress.json'),
              ('summary', 'analysis_summary.md')]


def _delivery_code_sets(text):
    """Parse the final-delivery construction. Returns (uncond, cond, order)
    as (set, set, list of canonical filenames) or (None, None, None)."""
    m = re.search(r'delivery = \[(.*?)present_files\(delivery\)', text, re.S)
    if not m:
        return None, None, None
    block = 'delivery = [' + m.group(1)
    assigns = dict(re.findall(
        r"(\w+)\s*=\s*f'[^']*\{exam_code\}_([\w.]+)'", block))

    def fname(var):
        if var in assigns:
            return assigns[var]
        for hint, f in _VAR_HINTS:
            if hint in var:
                return f
        return var            # unknown var stays loud — will never match prose

    uncond, cond, order = set(), set(), []

    def add(var, conditional):
        f = fname(var)
        (cond if conditional else uncond).add(f)
        if f not in order:
            order.append(f)

    lines = block.split('\n')
    seed = re.match(r'delivery = \[([^\]]*)\]', block)
    if seed:
        for var in re.findall(r'\w+', seed.group(1)):
            add(var, False)
    for i, line in enumerate(lines):
        am = re.search(r'delivery\.append\((\w+)\)', line)
        if am:
            guard = line if 'if ' in line else (lines[i - 1] if i else '')
            add(am.group(1), '.path.exists(' in guard)
    tail = re.search(r'delivery \+= \[([^\]]*)\]', block)
    if tail:
        for var in re.findall(r'\w+', tail.group(1)):
            add(var, False)
    return uncond, cond, order


_DELIV_SITES = [
    # (label, start-anchor regex, end-anchor regex, mode)
    ('S11-2 PART B', r'PART B — present_files \(all in one call',
     r'PART C — Handoff message:', 'tiered'),
    ('S11-3 FINAL DELIVERY', r'FINAL DELIVERY \(last batch',
     r'DO NOT DELIVER', 'tiered'),
    ('pre-delivery checklist expected set', r'PRE-DELIVERY CHECKLIST',
     r'Check 1:', 'braces'),
    ('QV item [19]', r'\n\[19\]', r'\n\[20\]', 'weak'),
    ('S11-2 PART C', r'PART C — Handoff message:', r'```', 'weak'),
]


def _tiered_site_sets(seg):
    """Parse a two-tier prose list. Returns (uncond, cond, order). A site
    with NO tier headers (the v2.48.1 PART B shape) reads as all-mandatory."""
    has_headers = ('MANDATORY —' in seg) or ('WHEN IT EXISTS' in seg)
    mode, uncond, cond, order = (None if has_headers else 'u'), set(), set(), []
    for line in seg.split('\n'):
        if 'MANDATORY —' in line:
            mode = 'u'
            continue
        if 'WHEN IT EXISTS' in line:
            mode = 'c'
            continue
        if mode is None:
            continue
        for f in re.findall(_DELIV_NAME_RE, line):
            (uncond if mode == 'u' else cond).add(f)
            if f not in order:
                order.append(f)
    return uncond, cond, order


def check_delivery_set_parity(read=_read):
    problems = []
    text = read('Framework_MockTestAnalyse.md')
    code_u, code_c, code_order = _delivery_code_sets(text)
    if code_u is None:
        return ["Framework_MockTestAnalyse.md: final-delivery code block "
                "(`delivery = [` … `present_files(delivery)`) not found — "
                "MS-11 has no ground truth; was the delivery code renamed?"]
    for label, start, end, mode in _DELIV_SITES:
        m = re.search(start + r'(.*?)' + end, text, re.S)
        if not m:
            problems.append(f"Framework_MockTestAnalyse.md: delivery site "
                            f"{label} not found (anchor {start!r}) — a rename "
                            f"must not silently disable MS-11")
            continue
        seg = m.group(1)
        if mode == 'tiered':
            su, sc, sorder = _tiered_site_sets(seg)
            if su != code_u or sc != code_c:
                problems.append(
                    f"Framework_MockTestAnalyse.md {label}: declared sets "
                    f"disagree with delivery code — site mandatory={sorted(su)} "
                    f"conditional={sorted(sc)}, code mandatory={sorted(code_u)} "
                    f"conditional={sorted(code_c)} (the DELIVERY-COUNT-DRIFT "
                    f"class; GAP-2026-08-14-S11-2-PARTB-UNFIXED)")
            want = [f for f in code_order if f in (su | sc)]
            if sorder != want:
                problems.append(
                    f"Framework_MockTestAnalyse.md {label}: file order "
                    f"{sorder} != delivery-code emission order {want} "
                    f"(GAP-2026-08-14-DELIVERY-ORDER-DRIFT)")
        elif mode == 'braces':
            fu = re.search(r'final:\s*\{([^}]*)\}', seg)
            fc = re.search(r'WHEN IT EXISTS:\s*\{([^}]*)\}', seg)
            su = set(re.findall(_DELIV_NAME_RE, fu.group(1))) if fu else set()
            sc = set(re.findall(_DELIV_NAME_RE, fc.group(1))) if fc else set()
            if su != code_u or sc != code_c:
                problems.append(
                    f"Framework_MockTestAnalyse.md {label}: expected sets "
                    f"disagree with delivery code — site mandatory={sorted(su)} "
                    f"conditional={sorted(sc)}, code mandatory={sorted(code_u)} "
                    f"conditional={sorted(code_c)}")
        else:  # weak
            for f in sorted(code_c):
                if f not in seg:
                    problems.append(
                        f"Framework_MockTestAnalyse.md {label}: conditional "
                        f"deliverable {f} not mentioned (the taxonomy.xlsx "
                        f"silent-drop came from exactly this omission)")
            nm = re.search(r'(\d+) mandatory', seg)
            if nm and int(nm.group(1)) != len(code_u):
                problems.append(
                    f"Framework_MockTestAnalyse.md {label}: claims "
                    f"{nm.group(1)} mandatory files but the delivery code has "
                    f"{len(code_u)} unconditional deliverables")
    return problems



# ── MS-12 ───────────────────────────────────────────────────────────────
# BATCH-CEILING. GAP-2026-08-16-STEP5-SESSION-EXHAUSTION / G-6, a pure
# cross-file desync. Framework_PYQCore EC-P37 settled the question in terms —
# "BATCH_SIZE is a pacing CEILING, not a floor", with the measurement that an
# inline session commonly admits ONE paper — while Framework_MockTestAnalyse
# S8-1 still read as a floor ("Processing 3 papers together in one go is
# MANDATORY", "MANDATORY AFTER EVERY BATCH OF 3") and S8-3 hardcoded exactly
# three checkmark lines. A model or an operator reading only the step file
# concluded that a 1-paper batch was a spec violation, and then either stalled
# for clarification or "fixed" it by widening the context budget — which EC-P37
# forbids, because it trades a longer run for a mid-batch context stall the
# per-paper save survives but the operator cannot interpret.
FLOOR_PATTERNS = [
    (r'MANDATORY AFTER EVERY BATCH OF 3',
     "asserts a batch FLOOR ('MANDATORY AFTER EVERY BATCH OF 3')"),
    (r'Processing 3 papers together in one go is MANDATORY',
     "asserts a batch FLOOR ('Processing 3 papers together in one go is MANDATORY')"),
    (r'BATCH SIZE = 3, STRICTLY ENFORCED, NO EXCEPTIONS',
     "asserts a batch FLOOR ('STRICTLY ENFORCED, NO EXCEPTIONS' without a ceiling "
     "qualifier)"),
]


def check_batch_ceiling(read=_read):
    """Every spec naming BATCH_SIZE must read it as a CEILING and cite EC-P37."""
    problems = []
    for name in SPECS:
        try:
            text = read(name)
        except FileNotFoundError:
            continue
        if 'BATCH_SIZE' not in text:
            continue
        for pat, why in FLOOR_PATTERNS:
            # A line QUOTING the old wording in order to explain why it was wrong is
            # not an assertion of it. Without this the fix for the defect trips the
            # gate written to catch the defect, and the only way to pass would be to
            # delete the explanation — which is how a corpus loses its defect record.
            for m in re.finditer(pat, text):
                line = text[text.rfind('\n', 0, m.start()) + 1:
                             text.find('\n', m.end())]
                if '"' in line or 'read as a FLOOR' in line:
                    continue
                problems.append(f'{name}: {why} — EC-P37 says it is a ceiling')
                break
        # EC-P37 is about admission on a CONTEXT-BOUNDED channel. A batched step with
        # no transport concept cannot admit fewer papers than its batch size for that
        # reason, so demanding the citation there is noise — and the v2.39 record is
        # explicit that a gate firing where it does not apply trains operators to
        # ignore gates. Scope the citation requirement to transport-bearing specs.
        transport_bound = any(k in text for k in (
            'partition_by_transport', 'CHANNEL PROBE', 'inline_budget'))
        if transport_bound and 'EC-P37' not in text:
            problems.append(
                f'{name}: names BATCH_SIZE and carries a context-bounded transport '
                f'channel, but never references EC-P37 — which is where the '
                f'ceiling-not-floor rule and its measurement live. A reader of this '
                f'file alone would conclude a 1-paper batch is a violation.')
    return problems


# ── MS-13 ───────────────────────────────────────────────────────────────
# PROBE-SELECTION. GAP-2026-08-16-STEP5-SESSION-EXHAUSTION / G-3. S8-0 was
# "ported in CONTRACT from Framework_PYQCount S5-0 with four Step-5-specific
# deviations", and probe-paper selection was not among the four — so "download
# the SMALLEST by fileSize" came across verbatim into a step whose admitted set
# is recency-first, where the smallest paper is almost never fetched and its
# payload is decoded, proven and thrown away. Measured: 107,968 characters, 54%
# of the whole budget, for zero papers. An inherited rule that is right in the
# source file and wrong in the destination is invisible to every other check in
# this repo, so the rule must be DECLARED wherever a probe exists.
def check_probe_selection(read=_read):
    """A spec with a channel probe must declare its probe-paper rule + divergence."""
    problems = []
    targets = SPECS + ['Framework_PYQCount.md']
    for name in targets:
        try:
            text = read(name)
        except FileNotFoundError:
            continue
        if 'CHANNEL PROBE' not in text:
            continue
        if not re.search(r'SMALLEST by fileSize|admitted\[0\]', text):
            problems.append(
                f'{name}: carries a CHANNEL PROBE but never states which paper it '
                f'probes. Silent inheritance of a sibling step\'s rule is exactly how '
                f'"SMALLEST" reached a recency-first step.')
        if 'P4f' not in text:
            problems.append(
                f'{name}: carries a CHANNEL PROBE but does not name deviation P4f, '
                f'which is where the Step-4/Step-5 divergence in probe-paper selection '
                f'is declared. Both files must name it, so neither can change its rule '
                f'without the other noticing.')
    return problems


ALL_CHECKS = [
    ('MS-1 PIN-FLOOR', check_pin_floor),
    ('MS-2 RETIRED-NAMES', check_retired_names),
    ('MS-3 STAMP-PARITY', check_stamp_parity),
    ('MS-4 COUNT-CLAIMS', check_count_claims),
    ('MS-5 GATE-PRESENCE', check_gate_presence),
    ('MS-6 SLUG-LITERALS', check_slug_literals),
    ('MS-7 QINDEX-FIELDS', check_qindex_fields),
    ('MS-8 DLBL-PARITY', check_dlbl_parity),
    ('MS-9 FOOTER-STEP5', check_footer_step5),
    ('MS-10 VERSION-PINS', check_version_pins),
    ('MS-11 DELIVERY-SET-PARITY', check_delivery_set_parity),
    ('MS-12 BATCH-CEILING', check_batch_ceiling),
    ('MS-13 PROBE-SELECTION', check_probe_selection),
]


# ── self-test ───────────────────────────────────────────────────────────
def self_test():
    passed = total = 0
    fails = []

    def check(name, cond):
        nonlocal passed, total
        total += 1
        if cond:
            passed += 1
        else:
            fails.append(name)

    def fake_reader(mapping):
        def _r(name, root=None):
            if name in mapping:
                return mapping[name]
            raise FileNotFoundError(name)
        return _r

    # MS-1: exact pin flagged, floor honored, low engine flagged
    bad = {'Framework_MockTestExplain.md':
               'x\n  MUST print\n  "SELF-TEST: 62/62 PASS" before\n',
           'Framework_PYQExplain.md': ''}
    check('ms1_exact_pin_flagged',
          any('exact self-test count' in p
              for p in check_pin_floor(read=fake_reader(bad), run=lambda f: 99)))
    ok = {'Framework_MockTestExplain.md':
              '"SELF-TEST: N/N PASS" with N == total (all pass) AND N >= 62 before any',
          'Framework_PYQExplain.md': ''}
    check('ms1_floor_form_clean_when_engine_meets_floor',
          check_pin_floor(read=fake_reader(ok), run=lambda f: 64) == [])
    check('ms1_floor_violated_when_engine_below',
          any('demands >= 62' in p
              for p in check_pin_floor(read=fake_reader(ok), run=lambda f: 10)))

    # MS-2: retired name in fence flagged; allowlisted line not; prose not
    fence = lambda body: f"prose Create_Complete ok\n```python\n{body}\n```\n"
    bads = {s: '' for s in SPECS}
    bads['Framework_MockTestExplain.md'] = fence("need Create_Complete docx")
    check('ms2_retired_in_fence_flagged',
          any('Create_Complete' in p for p in check_retired_names(read=fake_reader(bads))))
    allow = {s: '' for s in SPECS}
    allow['Framework_DeliveryFooter.md'] = fence("'Mock*_Create_Complete.docx',  # legacy")
    check('ms2_allowlisted_legacy_pattern_ok',
          check_retired_names(read=fake_reader(allow)) == [])
    prose_only = {s: '' for s in SPECS}
    prose_only['Framework_MockTestExplain.md'] = "Create_Complete was retired.\n"
    check('ms2_prose_mention_ok',
          check_retired_names(read=fake_reader(prose_only)) == [])

    # MS-3: drifted stamp flagged; matching clean
    # Both fixtures now carry ALL THREE stamp forms: since the presence rule was
    # added, a fixture missing a form is reported as a disarmed pattern, which is
    # the intended behaviour and would otherwise make these fixtures ambiguous.
    _stamps = ("'Generated by Framework_MockTestAnalyse v{v}',\n"
               "'Framework_MockTestAnalyse v{v}',\n"
               "f'framework_version: v{v}',\n")
    drift = {'Framework_MockTestAnalyse.md':
             "# Framework_MockTestAnalyse v2.47.1 — x\n```python\n"
             + _stamps.format(v='2.23') + "```\n"}
    check('ms3_drifted_stamp_flagged',
          any('v2.47' in p for p in check_stamp_parity(read=fake_reader(drift))))
    clean = {'Framework_MockTestAnalyse.md':
             "# Framework_MockTestAnalyse v2.47.1 — x\n```python\n"
             + _stamps.format(v='2.47') + "```\n"}
    check('ms3_matching_stamp_clean',
          check_stamp_parity(read=fake_reader(clean)) == [])
    # PRESENCE: a derived stamp leaves no literal to compare, which must FAIL rather
    # than pass quietly (release 2026.08.15.8).
    derived = {'Framework_MockTestAnalyse.md':
               "# Framework_MockTestAnalyse v2.47.1 — x\n```python\n"
               "f'{FRAMEWORK_VERSION_STAMP}',\n```\n"}
    check('ms3_derived_stamp_is_not_a_pass',
          any('no emitted stamp matches' in p
              for p in check_stamp_parity(read=fake_reader(derived))))

    # MS-4
    cc = {'Framework_MockTestAnalyse.md': 'EXACTLY 5 files at completion',
          'Framework_MockTestCreate.md': ''}
    check('ms4_literal_count_flagged',
          any('EXACTLY' in p for p in check_count_claims(read=fake_reader(cc))))
    check('ms4_word_form_flagged',
          any(check_count_claims(read=fake_reader(
              {'Framework_MockTestAnalyse.md': '',
               'Framework_MockTestCreate.md': 'delivers EXACTLY TWO files'}))))

    # MS-5
    gp = {'Framework_MockTestExplain.md': 'P10/0 here',
          'Framework_MockDeliver.md': 'if paper_slug != docx_slug:',
          'final_assembly.py': "_new_prefix == 'MOCK' ... G-COMMIT-COMPLETE/DUP"}
    check('ms5_all_gates_present_clean',
          check_gate_presence(read=fake_reader(gp)) == [])
    gp2 = dict(gp); gp2['Framework_MockTestExplain.md'] = 'gate deleted'
    check('ms5_missing_gate_flagged',
          any('P10/0' in p for p in check_gate_presence(read=fake_reader(gp2))))

    # MS-6
    sl = {s: '' for s in SPECS}
    sl['Framework_MockTestCreate.md'] = \
        "```python\n_docx = f'/x/{EXAM}_Mock{N}_Create.docx'\n```\n"
    check('ms6_literal_mockN_flagged',
          any('paper_slug' in p for p in check_slug_literals(read=fake_reader(sl))))
    sl2 = {s: '' for s in SPECS}
    sl2['Framework_MockTestCreate.md'] = \
        "```python\n_docx = f'/x/{EXAM}_{pp.paper_slug(paper_id)}_Create.docx'\n```\n"
    check('ms6_slug_derived_clean',
          check_slug_literals(read=fake_reader(sl2)) == [])

    # MS-7
    qf = {'final_assembly.py': '"q" "subtopic_id" "section" "subtopic" "difficulty"',
          'Framework_MockTestExplain.md':
              "## P10 x\nx.get('difficulty')\nx.get('nonexistent_key')\n"}
    probs = check_qindex_fields(read=fake_reader(qf))
    check('ms7_unknown_consumer_key_flagged',
          any('nonexistent_key' in p for p in probs))
    qf2 = {'final_assembly.py': '"subtopic_id"',
           'Framework_MockTestExplain.md': '## P10 x\n'}
    check('ms7_missing_writer_field_flagged',
          any('"q"' in p for p in check_qindex_fields(read=fake_reader(qf2))))

    # MS-8
    d1 = {'a.md': "bp.get('difficulty_labels', ['Easy', 'Medium', 'Hard'])",
          'b.md': "get('difficulty_labels', ['Simple', 'Medium', 'Hard'])"}
    check('ms8_divergent_defaults_flagged',
          any(check_dlbl_parity(read=fake_reader(d1), files=['a.md', 'b.md'])))
    d2 = {'a.md': "bp.get('difficulty_labels', ['Easy', 'Medium', 'Hard'])",
          'b.md': "get('difficulty_labels', ['Easy', 'Medium', 'Hard'])"}
    check('ms8_identical_defaults_clean',
          check_dlbl_parity(read=fake_reader(d2), files=['a.md', 'b.md']) == [])

    # MS-9
    f1 = {'Framework_DeliveryFooter.md':
          'FINAL DELIVERABLES x\n section_rules.md\n'}
    check('ms9_missing_files_flagged',
          len(check_footer_step5(read=fake_reader(f1))) == 2)
    f2 = {'Framework_DeliveryFooter.md':
          'FINAL DELIVERABLES x\n exam_config.json\n taxonomy.xlsx\n'}
    check('ms9_complete_list_clean',
          check_footer_step5(read=fake_reader(f2)) == [])

    # MS-10
    vp = {s: '' for s in SPECS}
    vp['Framework_MockDeliver.md'] = '# Framework_MockDeliver v1.12.1 — x\n'
    vp['Framework_MockTestCreate.md'] = \
        '# Framework_MockTestCreate v5.54.1 — x\ncompanion Framework_MockDeliver v9.0.0\n'
    check('ms10_future_pin_flagged',
          any('v9.0.0' in p for p in check_version_pins(read=fake_reader(vp))))
    vp['Framework_MockTestCreate.md'] = \
        '# Framework_MockTestCreate v5.54.1 — x\ncompanion Framework_MockDeliver v1.12.0\n'
    check('ms10_historical_pin_clean',
          check_version_pins(read=fake_reader(vp)) == [])

    # MS-11 — fixture mandated by the defect report: the v2.48.1 PART B text
    # MUST be flagged; the v2.48.2 fixed text MUST pass. If the v2.48.1 shape
    # passes, the check does not work.
    _CODE = (
        "```python\n"
        "    delivery = [rules_path]\n"
        "    if manifest_path: delivery.append(manifest_path)\n"
        "    if xlsx_path:     delivery.append(xlsx_path)\n"
        "    _ecfg_out = f'/mnt/user-data/outputs/{exam_code}_exam_config.json'\n"
        "    import os as _os2\n"
        "    if _os2.path.exists(_ecfg_out):\n"
        "        delivery.append(_ecfg_out)\n"
        "    import os as _os\n"
        "    _tax_path = f'/mnt/user-data/outputs/{exam_code}_taxonomy.xlsx'\n"
        "    if _os.path.exists(_tax_path): delivery.append(_tax_path)\n"
        "    delivery += [progress_path, summary_path]\n"
        "    present_files(delivery)\n"
        "```\n")
    _PARTB_V2481 = (          # the shipped v2.48.1 text — the actual defect
        "PART B — present_files (all in one call, in this order):\n"
        "  1. [ExamCode]_section_rules.md\n"
        "  2. [ExamCode]_subtopic_manifest.json\n"
        "  3. [ExamCode]_PYQ_Frequency.xlsx\n"
        "  4. [ExamCode]_exam_config.json\n"
        "  5. [ExamCode]_analysis_progress.json\n"
        "  6. [ExamCode]_analysis_summary.md\n"
        "  All 6 are delivered as downloadable chat attachments.\n")
    _PARTB_FIXED = (
        "PART B — present_files (all in one call, in the order the delivery "
        "code emits):\n"
        "  MANDATORY — every run:\n"
        "    1. [ExamCode]_section_rules.md\n"
        "    2. [ExamCode]_subtopic_manifest.json\n"
        "    3. [ExamCode]_PYQ_Frequency.xlsx\n"
        "  WHEN IT EXISTS — which is every normal run:\n"
        "    4. [ExamCode]_exam_config.json\n"
        "    5. [ExamCode]_taxonomy.xlsx\n"
        "  MANDATORY — every run (emitted last):\n"
        "    6. [ExamCode]_analysis_progress.json\n"
        "    7. [ExamCode]_analysis_summary.md\n")
    _S113_V2481 = (           # v2.48.1's renumbering — the order-drift defect
        "FINAL DELIVERY (last batch)\n"
        "  MANDATORY — every run:\n"
        "    1. [ExamCode]_section_rules.md\n"
        "    2. [ExamCode]_subtopic_manifest.json\n"
        "    3. [ExamCode]_PYQ_Frequency.xlsx\n"
        "    4. [ExamCode]_analysis_progress.json\n"
        "    5. [ExamCode]_analysis_summary.md\n"
        "  WHEN IT EXISTS — which is every normal run:\n"
        "    6. [ExamCode]_exam_config.json\n"
        "    7. [ExamCode]_taxonomy.xlsx\n"
        "DO NOT DELIVER\n")
    _S113_FIXED = (
        "FINAL DELIVERY (last batch)\n"
        "  MANDATORY — every run:\n"
        "    1. [ExamCode]_section_rules.md\n"
        "    2. [ExamCode]_subtopic_manifest.json\n"
        "    3. [ExamCode]_PYQ_Frequency.xlsx\n"
        "  WHEN IT EXISTS — which is every normal run:\n"
        "    4. [ExamCode]_exam_config.json\n"
        "    5. [ExamCode]_taxonomy.xlsx\n"
        "  MANDATORY — every run (emitted last):\n"
        "    6. [ExamCode]_analysis_progress.json\n"
        "    7. [ExamCode]_analysis_summary.md\n"
        "DO NOT DELIVER\n")
    _CHECKLIST = (
        "PRE-DELIVERY CHECKLIST (before every present_files call):\n"
        "  expected = per-batch: {analysis_progress.json}\n"
        "             final:     {section_rules.md, subtopic_manifest.json,\n"
        "                         PYQ_Frequency.xlsx,\n"
        "                         analysis_progress.json, analysis_summary.md}\n"
        "             final, additionally WHEN IT EXISTS: {exam_config.json, taxonomy.xlsx}\n"
        "  Check 1: assert\n")
    _QV19_OK = ("\n[19] Final set: the 5 mandatory files, + exam_config.json and\n"
                "     taxonomy.xlsx when written (=7 on a normal run)\n[20] x\n")
    _QV19_BAD = ("\n[19] Final set: the 6 mandatory files, + exam_config.json and\n"
                 "     taxonomy.xlsx when written\n[20] x\n")
    _PARTC = ("PART C — Handoff message:\n"
              "  (the S11-3 final set: 5 mandatory, plus exam_config.json and\n"
              "   taxonomy.xlsx when present)\n"
              "```\n")

    def _spec(partb, s113, qv19=_QV19_OK, partc=_PARTC):
        return {'Framework_MockTestAnalyse.md':
                _CODE + partb + partc + s113 + _CHECKLIST + qv19}

    cu, cc, corder = _delivery_code_sets(_CODE)
    check('ms11_code_sets_parsed',
          cu == {'section_rules.md', 'subtopic_manifest.json',
                 'PYQ_Frequency.xlsx', 'analysis_progress.json',
                 'analysis_summary.md'}
          and cc == {'exam_config.json', 'taxonomy.xlsx'}
          and corder == ['section_rules.md', 'subtopic_manifest.json',
                        'PYQ_Frequency.xlsx', 'exam_config.json',
                        'taxonomy.xlsx', 'analysis_progress.json',
                        'analysis_summary.md'])
    check('ms11_v2481_partb_flagged',            # the mandated fixture
          any('S11-2 PART B' in p and 'disagree' in p
              for p in check_delivery_set_parity(
                  read=fake_reader(_spec(_PARTB_V2481, _S113_FIXED)))))
    check('ms11_fixed_spec_clean',
          check_delivery_set_parity(
              read=fake_reader(_spec(_PARTB_FIXED, _S113_FIXED))) == [])
    check('ms11_s113_order_drift_flagged',
          any('S11-3' in p and 'emission order' in p
              for p in check_delivery_set_parity(
                  read=fake_reader(_spec(_PARTB_FIXED, _S113_V2481)))))
    check('ms11_qv19_count_mismatch_flagged',
          any('QV item [19]' in p and '6 mandatory' in p
              for p in check_delivery_set_parity(
                  read=fake_reader(_spec(_PARTB_FIXED, _S113_FIXED,
                                         qv19=_QV19_BAD)))))
    check('ms11_missing_site_flagged',
          any('not found' in p
              for p in check_delivery_set_parity(
                  read=fake_reader({'Framework_MockTestAnalyse.md':
                                    _CODE + _S113_FIXED + _CHECKLIST
                                    + _QV19_OK}))))
    # ── MS-12 / MS-13 — GAP-2026-08-16-STEP5-SESSION-EXHAUSTION ──────────────
    # Shipped in 2026.08.15.9 without fixtures. Gut check_batch_ceiling or
    # check_probe_selection to `return []` and the must-flag checks below must FAIL.
    _MIME = 'BATCH_SIZE = 3\npartition_by_transport(p, channel=c)\n'
    _floor = {'Framework_MockTestAnalyse.md':
                  _MIME + 'MANDATORY AFTER EVERY BATCH OF 3:\n  1. save\n'}
    check('ms12_floor_wording_flagged',
          any('FLOOR' in x for x in check_batch_ceiling(read=fake_reader(_floor))))
    _noec = {'Framework_MockTestAnalyse.md': _MIME + 'batch is min(3, admitted)\n'}
    check('ms12_missing_EC-P37_flagged_on_a_transport_spec',
          any('EC-P37' in x for x in check_batch_ceiling(read=fake_reader(_noec))))
    _ok = {'Framework_MockTestAnalyse.md':
               _MIME + 'BATCH_SIZE is a CEILING. See EC-P37.\n'}
    check('ms12_clean_spec_silent',
          check_batch_ceiling(read=fake_reader(_ok)) == [])
    # A batched spec with NO context-bounded channel must not be asked for EC-P37 —
    # it cannot admit fewer papers for that reason, and a gate that fires where it
    # does not apply trains operators to ignore gates (v2.39).
    _noxport = {'Framework_MockTestExplain.md': 'BATCH_SIZE = 4\nplain prose\n'}
    check('ms12_silent_on_a_spec_with_no_transport',
          check_batch_ceiling(read=fake_reader(_noxport)) == [])

    _p_undecl = {'Framework_MockTestAnalyse.md':
                     'A2. CHANNEL PROBE — download one paper.\n'}
    check('ms13_undeclared_probe_paper_flagged',
          any('probes' in x for x in check_probe_selection(read=fake_reader(_p_undecl))))
    _p_nodev = {'Framework_MockTestAnalyse.md':
                    'A2. CHANNEL PROBE — the SMALLEST by fileSize.\n'}
    check('ms13_undeclared_divergence_flagged',
          any('P4f' in x for x in check_probe_selection(read=fake_reader(_p_nodev))))
    _p_ok = {'Framework_MockTestAnalyse.md':
                 'A2. CHANNEL PROBE — admitted[0]. Deviation P4f declares the divergence.\n'}
    check('ms13_declared_probe_rule_silent',
          check_probe_selection(read=fake_reader(_p_ok)) == [])
    check('ms13_silent_on_a_spec_with_no_probe',
          check_probe_selection(read=fake_reader({'Framework_MockDeliver.md': 'no probe here'})) == [])


    print(f"SELF-TEST: {passed}/{total} PASS")
    if fails:
        print("FAILED: " + ", ".join(fails))
    return passed == total


def main(argv):
    if '--self-test' in argv:
        return 0 if self_test() else 1
    total = 0
    for label, fn in ALL_CHECKS:
        try:
            problems = fn()
        except FileNotFoundError as e:
            problems = [f"required file missing: {e}"]
        status = '✅ 0 issues' if not problems else f'❌ {len(problems)} issue(s)'
        print(f"{label}: {status}")
        for p in problems:
            print(f"   - {p}")
        total += len(problems)
    print(f"\nMOCK-SYNC-AUDIT: {'OK — all checks agree' if total == 0 else f'{total} issue(s) found'}")
    return 0 if total == 0 else 1


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
