#!/usr/bin/env python3
"""
SPEC SECTION MAP GENERATOR — GAP-2026-08-16-STEP5-SESSION-EXHAUSTION (Fix A).

Builds SPEC_SECTIONS.json: for every Framework_*.md, the line span of each of its own
'## ' and '### ' headers, plus the byte/token/view-call cost of each span.

WHY THIS EXISTS. Framework_PYQCore EC-P42. SKILL Rule 2 mandates reading every routed
.md IN FULL before any work. For trigger PYQExtract that is 556,834 B / ~139,208 tok /
>=36 view calls, MANDATORY, EVERY SESSION, on a step that is inherently multi-session.
In the reference incident 40 of session 1's 50 tool calls went to reading the
specification and the step stalled before its first productive operation. A session
that cannot clear the corpus never executes the synthesis, QV, summary or schema
sections, so it must not pay for them — but a reduced read is only safe if the ranges
are EXACT, and a hand-copied line number is a second definition of the file's own
structure that will drift on the first edit that adds a paragraph.

So the map is DERIVED, never declared. It is regenerated by gen_manifest.py, tracked in
MANIFEST.json by sha256, and verified by bootstrap.py like any other artefact. If the
spec changes and the map is not regenerated, the manifest check fails the build BEFORE
anybody reads a stale range.

THE MAP IS A READ AID AND NEVER A SECOND SOURCE OF TRUTH. It contains no spec content —
only line numbers into the verified file. Every read still comes out of the spec itself.
This is deliberate: a digest that carried copies of the fences would be a duplicate of
the source of truth inside a corpus whose entire integrity model is byte-verification.

    python3 spec_sections.py            # write SPEC_SECTIONS.json
    python3 spec_sections.py --check    # exit 1 if the committed map is stale
    python3 spec_sections.py --self-test
"""
import hashlib
import json
import os
import re
import sys

OUT = 'SPEC_SECTIONS.json'
HEADER_RE = re.compile(r'^(#{2,3})\s+(\S.*?)\s*$')

# Framework_MockTestAnalyse §S8-0b. Sections a NON-FINAL session never executes. Named
# by the '## §N' prefix of their own header so a renamed subsection cannot silently
# fall out of the set. A section absent from this list is READ — the default is safe.
FINAL_ONLY_PREFIXES = {
    # v2 (2026-08-22, GAP-2026-08-22-STEP9-READ-SET): Step 9's closing sections.
    # §21/§23/§24 are per-session law and stay in the NON-FINAL read; only the
    # end-of-mock report, its §R9 disclosure input and the editorial appendix are
    # FINAL-only. The reduction is deliberately small — the durable property is
    # has_read_set, which covers the MockExplain/TestExplain route's SPEC-BUDGET
    # by design instead of by residual headroom.
    'Framework_MockTestExplain.md': (
        '## §20', '## §22', '## APPENDIX A',
    ),
    'Framework_MockTestAnalyse.md': (
        '## §1-6', '## §5', '## §6', '## §9', '## §10',
        '## §12', '## §13', '## §14', '## §15', '## §16',
        '## DEFINITION OF DONE', '## HUMAN REVIEW', '## SUGGESTED', '## STATISTICS',
    ),
    # v3 (2026-08-22, GAP-1B-STEP7-READ-SET): Step 7's Final-Assembly family and
    # close-out pair. TRAILING SPACES ARE LOAD-BEARING: '## S13-9 ' must NOT match
    # '## S13-9A' — the post-delivery footer is PER-DELIVERY law (F1 after every
    # non-final batch) and stays in every read. '## S13-4' deliberately unguarded:
    # it matches S13-4, S13-4b and S13-4c, all three Final-Assembly-only. All S4
    # batch law, S13-9A and every gate section stay in the NON-FINAL read.
    'Framework_MockTestCreate.md': (
        '## S13-1 ', '## S13-2 ', '## S13-3 ', '## S13-4',
        '## S13-REGCHECK', '## S13-QINDEX',
        '## S13-5 ', '## S13-6 ', '## S13-7 ', '## S13-8 ', '## S13-9 ',
        '## S17-1', '## S17-2',
    ),
    # v4 (2026-08-22, STEP6-READ-SET): Step 6's input phase (B1-only) + closing
    # phase (B3-only). TRAILING SPACES ARE LOAD-BEARING on the single-digit
    # entries: '## §1 ' would be needed to exclude §10/§12/§13/§15/§16 if §1 were
    # ever listed — it is NOT listed (S1-7 defines B2 resume). '## S2-MANIFEST'
    # deliberately unguarded: it matches both S2-MANIFEST and
    # S2-MANIFEST-COMPLETENESS, both B1-only. §5 is NOT here: B2 recomputes
    # zp_slot/MAX_ZERO from §5-1/§5-2 (explicitly not stored in blueprint.json).
    'Framework_Blueprint.md': (
        '## §2 ', '## §3 ', '## §6 ', '## §7 ', '## §10 ',
        '## §12 ', '## §13 ', '## §15 ',
        '## S2-MANIFEST',
        '## DEFINITION OF DONE', '## DoD additions',
    ),
    # v5 (2026-08-23, GAP-2026-08-23-PYQSCAN-SPECBUDGET): the PYQScan route sat 67 B
    # under the 250,000 B SPEC-BUDGET line at 36e6ebf; DeliveryFooter v1.23 (+1,410 B,
    # on all 23 routes) carried it over, and no spec on the route declared a read set —
    # the gate's uncovered-route condition, found at DEPLOY. The margin was the defect:
    # any growth in any of three specs re-breaches it, so the durable property is
    # has_read_set, exactly as the MockTestExplain v2 note above says.
    # §11 (EXAM-AGNOSTIC GUARANTEE) is a close-out attestation LIST — every rule it
    # names lives in its own section, all of which stay in every read. §12 is the
    # DEFINITION OF DONE checklist, consulted only by the session that closes the
    # books. §10 is NOT here: it governs the per-batch present_files call of every
    # NON-FINAL scan session. The hosted S2-3 is NOT here: it is PYQDraft's working
    # law, and PYQDraft always reads FINAL (bootstrap one-shot rule, same GAP).
    'Framework_PYQCore.md': (
        '## §11', '## §12',
    ),
}

# Measured in the container, 2026-08-16. The view tool truncates output above ~16,000
# characters INCLUDING explicitly ranged reads; a bash heredoc returned 188,024
# characters intact in one call. Both numbers are reported so the operator can see why
# the spec says to read with `sed -n` and not with view.
VIEW_TRUNCATE_CHARS = 16000
BASH_SAFE_CHARS = 150000


def sha256_file(path):
    with open(path, 'rb') as fh:
        return hashlib.sha256(fh.read()).hexdigest()


def section_spans(path):
    """Line spans of every '## '/'### ' header in one spec. 1-indexed, inclusive."""
    with open(path, encoding='utf-8') as fh:
        lines = fh.read().split('\n')
    # A '#' inside a fence is a python comment, not a header. Tracking fence state is
    # not optional: Framework_MockTestAnalyse carries 42 python fences whose comment
    # lines would otherwise be read as section boundaries and shred the map.
    in_fence = False
    heads = []
    for i, ln in enumerate(lines, 1):
        if ln.lstrip().startswith('```'):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        m = HEADER_RE.match(ln)
        if m:
            heads.append((i, m.group(0).strip()))
    n = len(lines)
    out = []
    for idx, (start, title) in enumerate(heads):
        end = heads[idx + 1][0] - 1 if idx + 1 < len(heads) else n
        span_bytes = sum(len(lines[j - 1].encode('utf-8')) + 1
                         for j in range(start, end + 1))
        out.append({'title': title, 'start': start, 'end': end,
                    'lines': end - start + 1, 'bytes': span_bytes})
    return out, n


def build(repo_dir='.'):
    specs = sorted(f for f in os.listdir(repo_dir)
                   if f.startswith('Framework_') and f.endswith('.md'))
    doc = {'_generated_by': 'spec_sections.py',
           '_note': ('Line numbers only — never spec content. Regenerate with '
                     'gen_manifest.py; bootstrap.py verifies the sha256.'),
           'view_truncate_chars': VIEW_TRUNCATE_CHARS,
           'bash_safe_chars': BASH_SAFE_CHARS,
           'files': {}}
    for name in specs:
        path = os.path.join(repo_dir, name)
        spans, total_lines = section_spans(path)
        total_bytes = os.path.getsize(path)
        final_only = FINAL_ONLY_PREFIXES.get(name, ())
        # The skip must CASCADE. A '### S5-3' is a child of '## §5' and inherits its
        # class; matching prefixes alone kept S5-2 and S5-3 — 174 KB, a third of the
        # file — inside a "reduced" read that was then barely reduced at all. Skipping
        # is therefore decided by SPAN CONTAINMENT against the top-level ('## ') spans,
        # so a subsection can never be separated from the section that governs it.
        top = [sp for sp in spans if sp['title'].startswith('## ')]
        # A '## ' span in `spans` ends at the NEXT HEADER OF ANY LEVEL, which for a
        # section with subsections is two lines later — it never contained its own
        # children, so the cascade silently did nothing and the "reduced" set stayed
        # 82% of the file. Top-level extent must be measured against the next '## '
        # header only.
        top_extent = []
        for i, sp in enumerate(top):
            end = top[i + 1]['start'] - 1 if i + 1 < len(top) else total_lines
            top_extent.append((sp['title'], sp['start'], end))
        skip_ranges = [(a, b) for title, a, b in top_extent
                       if final_only and title.startswith(tuple(final_only))]

        def _is_final_only(sp):
            return any(a <= sp['start'] <= b for a, b in skip_ranges)

        reduced, skipped = [], []
        for sp in spans:
            (skipped if _is_final_only(sp) else reduced).append(sp)
        red_bytes = sum(sp['bytes'] for sp in reduced) if final_only else total_bytes
        doc['files'][name] = {
            'sha256': sha256_file(path),
            'lines': total_lines,
            'bytes': total_bytes,
            'est_tokens': total_bytes // 4,
            'view_calls': -(-total_bytes // VIEW_TRUNCATE_CHARS),
            'bash_calls': max(1, -(-total_bytes // BASH_SAFE_CHARS)),
            'has_read_set': bool(final_only),
            'reduced_bytes': red_bytes,
            'reduced_est_tokens': red_bytes // 4,
            'reduced_bash_calls': max(1, -(-red_bytes // BASH_SAFE_CHARS)),
            'final_only_titles': [sp['title'] for sp in skipped],
            'sections': spans,
        }
    return doc


def read_plan(doc, name, session_class):
    """The exact ranges to read. 'FINAL' is always the whole file, no exception."""
    info = doc['files'][name]
    if session_class.upper() == 'FINAL' or not info['has_read_set']:
        return [(1, info['lines'])]
    final_only = tuple(info['final_only_titles'])
    keep = [sp for sp in info['sections'] if sp['title'] not in final_only]
    ranges, cur = [], None
    for sp in keep:                       # merge adjacent spans into one sed call
        if cur and sp['start'] == cur[1] + 1:
            cur = (cur[0], sp['end'])
        else:
            if cur:
                ranges.append(cur)
            cur = (sp['start'], sp['end'])
    if cur:
        ranges.append(cur)
    return ranges


def self_test():
    passed = total = 0
    fails = []

    def check(name, cond):
        nonlocal passed, total
        total += 1
        if cond:
            passed += 1
        else:
            fails.append(name)

    doc = build('.')
    ma = 'Framework_MockTestAnalyse.md'
    check('t_every_spec_mapped', len(doc['files']) >= 20)
    check('t_spans_are_contiguous_and_cover_the_file',
          all(s['sections'][i]['end'] + 1 == s['sections'][i + 1]['start']
              for s in doc['files'].values()
              for i in range(len(s['sections']) - 1)))
    check('t_last_span_reaches_eof',
          all(s['sections'][-1]['end'] == s['lines']
              for s in doc['files'].values() if s['sections']))
    # A '#' inside a python fence must NEVER be read as a header. This is the defect
    # that would silently shred the map on the largest spec in the corpus.
    check('t_fence_comments_are_not_headers',
          all(not sp['title'].startswith('# ')
              for sp in doc['files'][ma]['sections']))
    check('t_step5_has_a_read_set', doc['files'][ma]['has_read_set'])
    check('t_reduced_is_smaller_than_full',
          doc['files'][ma]['reduced_bytes'] < doc['files'][ma]['bytes'])
    check('t_reduced_saves_at_least_a_third',
          doc['files'][ma]['reduced_bytes'] < doc['files'][ma]['bytes'] * 0.7)
    check('t_final_reads_everything',
          read_plan(doc, ma, 'FINAL') == [(1, doc['files'][ma]['lines'])])
    check('t_nonfinal_reads_less_than_final',
          sum(b - a + 1 for a, b in read_plan(doc, ma, 'NON-FINAL'))
          < doc['files'][ma]['lines'])
    check('t_nonfinal_ranges_are_ordered_and_disjoint',
          all(read_plan(doc, ma, 'NON-FINAL')[i][1] < read_plan(doc, ma, 'NON-FINAL')[i + 1][0]
              for i in range(len(read_plan(doc, ma, 'NON-FINAL')) - 1)))
    # A spec with no declared read set must default to the WHOLE file. Defaulting to a
    # subset would silently under-read every spec nobody has classified yet.
    # GAP-2026-08-23-AUDITSYNC-FIXTURE-STALE (same class, same release): this
    # fixture named Framework_PYQCore.md as its unclassified example and broke
    # the moment v5 classified it. The property under test is the DEFAULT — any
    # spec with no read set reads in full — not any particular file, so the
    # example is picked from whatever is unclassified NOW. If one day every
    # spec is classified, the next(...) fails loudly and the fixture must be
    # rebuilt on a synthetic spec, not deleted.
    _uncls = next(n for n in sorted(doc['files'])
                  if not doc['files'][n]['has_read_set'])
    check('t_unclassified_spec_reads_in_full',
          read_plan(doc, _uncls, 'NON-FINAL')
          == [(1, doc['files'][_uncls]['lines'])])
    # Step 9 (GAP-2026-08-22-STEP9-READ-SET): covered, small by design, and the
    # skip list is EXACTLY the three declared sections — a fourth section
    # appearing here means a header promotion leaked a span into the skip set.
    me = 'Framework_MockTestExplain.md'
    check('t_step9_has_a_read_set', doc['files'][me]['has_read_set'])
    check('t_step9_reduced_is_smaller',
          doc['files'][me]['reduced_bytes'] < doc['files'][me]['bytes'])
    check('t_step9_skips_exactly_the_declared_sections',
          sorted(t.split(' — ')[0] for t in doc['files'][me]['final_only_titles'])
          == ['## APPENDIX A', '## §20', '## §22'])
    check('t_step9_final_reads_everything',
          read_plan(doc, me, 'FINAL') == [(1, doc['files'][me]['lines'])])
    _keep9 = read_plan(doc, me, 'NON-FINAL')
    def _covered9(title_prefix):
        sp = next(x for x in doc['files'][me]['sections']
                  if x['title'].startswith(title_prefix))
        return any(a <= sp['start'] <= b for a, b in _keep9)
    check('t_step9_nonfinal_keeps_the_per_session_law',
          _covered9('## §21') and _covered9('## §23') and _covered9('## §24')
          and _covered9('## FOOTER') and not _covered9('## §20')
          and not _covered9('## §22') and not _covered9('## APPENDIX A'))
    check('t_sha_matches_disk',
          doc['files'][ma]['sha256'] == sha256_file(ma))
    print(f'SELF-TEST: {passed}/{total} PASS')
    if fails:
        print('FAILED: ' + ', '.join(fails))
    return passed == total


def main():
    if '--self-test' in sys.argv:
        sys.exit(0 if self_test() else 1)
    doc = build('.')
    text = json.dumps(doc, indent=2, ensure_ascii=False) + '\n'
    if '--check' in sys.argv:
        if not os.path.exists(OUT):
            print(f'STALE: {OUT} is missing. Run gen_manifest.py.')
            sys.exit(1)
        if open(OUT, encoding='utf-8').read() != text:
            print(f'STALE: {OUT} does not match the specs on disk. Run gen_manifest.py.')
            sys.exit(1)
        print(f'{OUT} is current — {len(doc["files"])} spec(s) mapped.')
        sys.exit(0)
    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write(text)
    print(f'{OUT} written — {len(doc["files"])} spec(s) mapped.')


if __name__ == '__main__':
    main()
